[package]
name = "file_copy_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3"
sha2 = "0.9.5"
hex = "0.4.3"
tempdir = "0.3"